# Site settings
title: city hanok
tagline: Recording the appearance of Hanok in the city
email: mang2111@gmail.com
description: "I want to record the appearance of hanok in the city as a tourist destination, residential space, and commercial facility by following the various landscapes and traces surrounding it."
author: somang
baseurl: "/"
url: "https://cityhanok.com"
locale: "ko_KR"
thumbnail: "/img/thumbnail.jpg"

# Socail Profiles
instagram_username: city_hanok
facebook_username: city_hanok
linkedin_username: somang2020
# Build settings
markdown: kramdown
permalink: /:title
paginate: 8

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false

# 블로그 disqus shortname
disqus:
  shortname: cityhanok
